language: node_js

node_js:
  - "7.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
	firebase deploy --token "$FIREBASE_TOKEN"
firebase deploy --token "1/z2MtaKLeoHv3EeBmz_8gU_80cTmjQ2xaXBG8d58FqEtrS3jnsEhZx7nBnM_Q64dN"
1/z2MtaKLeoHv3EeBmz_8gU_80cTmjQ2xaXBG8d58FqEtrS3jnsEhZx7nBnM_Q64dN
