language: node_js

node_js:
  - "7.3"

branches:
  only:
    - master

script:
  - npm run build

after_script:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
