language: node_js

node_js:
  - "7.3"

addons:
  sonarcloud:
    organization: "mcdostone-github"
    token: $SONAR_TOKEN

branches:
  only:
    - master

script:
  - sonar-scanner
  - npm run build
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
