language: node_js

node_js:
  - "7.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run build

after_success:
  - firebase deploy --token  --token=${FIREBASE_TOKEN}
